/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParticipantDetailsRouteImport } from './routes/participant-details'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCreateRouteImport } from './routes/admin.create'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AttemptAttemptIdRouteImport } from './routes/attempt.$attemptId'
import { Route as QuizOfflineCheckRouteImport } from './routes/quiz.offline-check'
import { Route as ResultAttemptIdRouteImport } from './routes/result.$attemptId'
import { Route as ApiPublicConnectivityCheckRouteImport } from './routes/api/public/connectivity-check'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantDetailsRoute = ParticipantDetailsRouteImport.update({
  id: '/participant-details',
  path: '/participant-details',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AttemptAttemptIdRoute = AttemptAttemptIdRouteImport.update({
  id: '/attempt/$attemptId',
  path: '/attempt/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizOfflineCheckRoute = QuizOfflineCheckRouteImport.update({
  id: '/quiz/offline-check',
  path: '/quiz/offline-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultAttemptIdRoute = ResultAttemptIdRouteImport.update({
  id: '/result/$attemptId',
  path: '/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConnectivityCheckRoute =
  ApiPublicConnectivityCheckRouteImport.update({
    id: '/api/public/connectivity-check',
    path: '/api/public/connectivity-check',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/participant-details': typeof ParticipantDetailsRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/attempt/$attemptId': typeof AttemptAttemptIdRoute
  '/quiz/offline-check': typeof QuizOfflineCheckRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/connectivity-check': typeof ApiPublicConnectivityCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/participant-details': typeof ParticipantDetailsRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/attempt/$attemptId': typeof AttemptAttemptIdRoute
  '/quiz/offline-check': typeof QuizOfflineCheckRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/connectivity-check': typeof ApiPublicConnectivityCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/participant-details': typeof ParticipantDetailsRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/results': typeof AdminResultsRoute
  '/attempt/$attemptId': typeof AttemptAttemptIdRoute
  '/quiz/offline-check': typeof QuizOfflineCheckRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/connectivity-check': typeof ApiPublicConnectivityCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/participant-details'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/questions'
    | '/admin/results'
    | '/attempt/$attemptId'
    | '/quiz/offline-check'
    | '/result/$attemptId'
    | '/admin/'
    | '/api/public/connectivity-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/participant-details'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/questions'
    | '/admin/results'
    | '/attempt/$attemptId'
    | '/quiz/offline-check'
    | '/result/$attemptId'
    | '/admin'
    | '/api/public/connectivity-check'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/participant-details'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/questions'
    | '/admin/results'
    | '/attempt/$attemptId'
    | '/quiz/offline-check'
    | '/result/$attemptId'
    | '/admin/'
    | '/api/public/connectivity-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ParticipantDetailsRoute: typeof ParticipantDetailsRoute
  AttemptAttemptIdRoute: typeof AttemptAttemptIdRoute
  QuizOfflineCheckRoute: typeof QuizOfflineCheckRoute
  ResultAttemptIdRoute: typeof ResultAttemptIdRoute
  ApiPublicConnectivityCheckRoute: typeof ApiPublicConnectivityCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant-details': {
      id: '/participant-details'
      path: '/participant-details'
      fullPath: '/participant-details'
      preLoaderRoute: typeof ParticipantDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/attempt/$attemptId': {
      id: '/attempt/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/attempt/$attemptId'
      preLoaderRoute: typeof AttemptAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/offline-check': {
      id: '/quiz/offline-check'
      path: '/quiz/offline-check'
      fullPath: '/quiz/offline-check'
      preLoaderRoute: typeof QuizOfflineCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$attemptId': {
      id: '/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof ResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connectivity-check': {
      id: '/api/public/connectivity-check'
      path: '/api/public/connectivity-check'
      fullPath: '/api/public/connectivity-check'
      preLoaderRoute: typeof ApiPublicConnectivityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCreateRoute: typeof AdminCreateRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreateRoute: AdminCreateRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ParticipantDetailsRoute: ParticipantDetailsRoute,
  AttemptAttemptIdRoute: AttemptAttemptIdRoute,
  QuizOfflineCheckRoute: QuizOfflineCheckRoute,
  ResultAttemptIdRoute: ResultAttemptIdRoute,
  ApiPublicConnectivityCheckRoute: ApiPublicConnectivityCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
